resolver: lts-16.6
packages:
- '.'
extra-deps:
- algebraic-graphs-0.5
- unordered-containers-0.2.10.0
- selective-0.3
- html-entities-1.1.4.3
- mmorph-1.1.3
- exceptions-0.10.4
- semigroups-0.18.3
- xeno-0.3.5.2
- Cabal-3.2.0.0@sha256:d0d7a1f405f25d0000f5ddef684838bc264842304fd4e7f80ca92b997b710874,27320
- parsec-3.1.14.0
- text-1.2.4.0

# for weeder tool
#   https://github.com/ndmitchell/weeder
# ghc-options: {"$locals": -ddump-to-file -ddump-hi}
